substitutions:
  devicename: c6-relay-2ch
  friendly_name: C6 Relay 2CH

  # Relays connector: CH1=IO19, CH2=IO18
  relay1_pin: GPIO19
  relay2_pin: GPIO18

  # EX connector: IN1=IO23, IN2=IO22
  di1_pin: GPIO23
  di2_pin: GPIO22

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

logger:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: gpio
    name: Relay 1
    pin: ${relay1_pin}
    id: relay1

  - platform: gpio
    name: Relay 2
    pin: ${relay2_pin}
    id: relay2

binary_sensor:
  - platform: gpio
    name: DI1
    pin:
      number: ${di1_pin}
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    name: DI2
    pin:
      number: ${di2_pin}
      mode: INPUT_PULLUP
      inverted: true
